#! /usr/bin/env lua

local laz = require "llang"
local ut = require "utils"

local function usage()
  return "Usage: " .. arg[0] .. "[options] path/<source_file>"
end

local isInteractive = arg[1] == "-i"
local isDebug = #arg > 1 and arg[1] == "-debug" or isInteractive
local path = not isInteractive and arg[#arg] or #arg > 1 and table.concat(arg, " ", 2)

if path == nil and not isInteractive then 
  print(usage())
  os.exit(1)
end

if not isInteractive and not ut.fileExists(path) then
  print ("LAZ1 file ".. path .. " not found")
  os.exit(1)
end


local fh = not isInteractive and io.open(path, "rb")
local line = not isInteractive and fh:read("*line") or path or io.read()

local l = 1
local d = ut.Debug(isDebug)
local ip = laz.Interpreter()
local vm = laz.VM()

while line do    
    local codeList = ip.compile(line)
    d.debug(print, "Code List")
    d.debug(ut.printtable, codeList)
    status, err =  pcall(vm.run, codeList)
    status = status or ut.errorHandler("VM error in line: ".. l .. "\n" .. line, err)
    if not isInteractive then
      line = fh:read("*line")
      l = l + 1
     else
       d.debug(print, "Stack after calculations")
       vm.printStack()
       line = io.read()
    end
end
status = not isInteractive and fh:close()

-- print stack
d.debug(print, "Stack after calculations")
if isDebug then vm.printStack() end