name: run-test-actions
run-name: ${{ github.actor }} run tests
on:
 push:
  branches: [master]
 pull_request:
  branches: [master]

jobs:
 run_tests:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - name: Install lua and deps
     run: sudo apt-get -y update && sudo apt-get -y install bash lua5.3 lua-inspect lua-unit lua-lpeg lua-any luakit luarocks
   - name: run tests
     run: bash scripts/run_tests.sh
